version: "3.7"

services:
  wordcount:
    image: karamelsoft/wordcount:latest
    command: flink run --jobmanager jobmanager:8081 /app/app.jar
    deploy:
      restart_policy:
        condition: none
    networks:
      - flink

networks:
  flink:
    external: true
