version: "3.7"

services:

  rabbitmq:
    image: rabbitmq:management-alpine
    ports:
      - "15672:15672"
    networks:
      - dim3

  postgres:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
    networks:
      - dim3

  jobmanager:
    image: flink
    ports:
      - "8081:8081"
    depends_on:
      - rabbitmq
      - postgres
    command: jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    networks:
      - dim3

  taskmanager:
    image: flink
    depends_on:
      - rabbitmq
      - postgres
      - jobmanager
    command: taskmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    networks:
      - dim3
    deploy:
      mode: replicated
      replicas: 3

networks:
  dim3:
    external: true
